name: llamacpp_tools
description: Tools to manage llama.cpp local setup (detecting, downloading or building, running).
version: 0.3.0
homepage: https://github.com/agilord/llamacpp_tools
topics:
  - llamacpp
  - llama-cpp
  - cli
  - llm
  - tool

environment:
  sdk: '^3.9.0'

dependencies:
  args: ^2.6.0
  crypto: ^3.0.6
  gguf: ^0.1.1
  html: ^0.15.6
  http: ^1.4.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  process_visor: ^0.3.1
  llamacpp_rpc_client: ^0.2.0

dev_dependencies:
  build_runner: ^2.6.1
  huggingface_tools: ^0.1.0
  json_serializable: ^6.10.0
  lints: ^6.0.0
  test: ^1.25.14
