name: llamacpp_tools
description: Tools to manage llama.cpp local setup (detecting, downloading or building).
version: 0.1.0
homepage: https://github.com/agilord/llamacpp_tools
topics:
  - cli
  - llm
  - tool
  - setup

environment:
  sdk: '^3.8.0'

dependencies:
  args: ^2.6.0
  html: ^0.15.6
  http: ^1.4.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
